x-common-config: &common-config
  # Common volumes for all services
  volumes:
    - ./src:/ros2_ws/src    
    # - ./data:/ros2_ws/data              # Mount only the src directory
    # - ./build:/ros2_ws/build              # Mount the build directory
    # - ./install:/ros2_ws/install          # Mount the install directory
    - /tmp/.X11-unix:/tmp/.X11-unix:ro    # X11 socket
    - ${HOME}/.Xauthority:/home/root/.Xauthority # X11 authentication
    - /dev/dri:/dev/dri                   # GPU access
    - ./logs:/root/.ros/log/              # Mount logs directory
    - ./worlds:/root/.gazebo/worlds/          # Mount worlds directory

  # Common environment variables
  environment:
    - DISPLAY=${DISPLAY}
    - QT_X11_NO_MITSHM=1
    - NVIDIA_VISIBLE_DEVICES=all
    - NVIDIA_DRIVER_CAPABILITIES=all
    - TURTLEBOT3_MODEL=waffle
    - ROS_DOMAIN_ID=42
    - ROS_LOCALHOST_ONLY=0
    - ROS_DISTRO=humble
    - GZ_PARTITION=0
    - GZ_IP=127.0.0.1

  # Common settings
  user: root
  ipc: host
  network_mode: host
  privileged: true
  stop_grace_period: 2s
  mem_limit: 4g
  # Common runtime for GPU access
  runtime: nvidia